baseURL: https://modelica.org
title: Modelica
theme: ma-hugo-theme
params:
  logo: /images/ma-logos/dark/m-ball.svg
  favicon: /images/m-ball-favicon.svg
  darkMode: true
  email: board@modelica.org
  uacode: UA-145375737-1
  linkedin: modelica-association
  youtube: modelicaassociation
menu:
  main:
    - name: Association
      pageRef: /association
      weight: 1

    - name: Projects
      weight: 2
    - name: Coordination
      pageRef: /projects/coordination
      parent: Projects
      weight: 1
    - name: Language
      pageRef: /projects/language
      parent: Projects
      weight: 2

    - name: Libraries
      pageRef: /libraries
      weight: 3

    - name: Tools
      pageRef: /tools
      weight: 4

    - name: Community
      weight: 5
    - name: Consulting
      pageRef: /community/consulting
      parent: Community
      weight: 1
    - name: Development
      pageRef: /community/development
      parent: Community
      weight: 2
    - name: Community Projects
      pageRef: /community/projects
      parent: Community
      weight: 3
    - name: Training
      pageRef: /community/training
      parent: Community
      weight: 4
    - name: Usergroups
      pageRef: /community/usergroups
      parent: Community
      weight: 5

    - name: Publications
      weight: 6
    - name: Books
      pageRef: /publications/books
      parent: Publications
      weight: 1
    - name: Proceedings
      pageRef: /publications/proceedings
      parent: Publications
      weight: 2

    - name: Events
      weight: 7
    - name: All Past and Upcoming Events
      pageRef: /events
      parent: Events
      weight: 1
    - name: Asian Modelica & FMI Conference 2026
      pageRef: /events/asian2026
      parent: Events
      weight: 2    
    - name: American Modelica & FMI Conference 2026
      pageRef: /events/american2026
      parent: Events
      weight: 3    
    - name: International Modelica & FMI Conference 2027
      pageRef: /events/modelica2027
      parent: Events
      weight: 4
    - name: Related Events
      pageRef: /events/related
      parent: Events
      weight: 5

    - name: News
      pageRef: /news
      weight: 8
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 3
